immediate_health_check:
    path: /healthcheck
    controller: IM\Fabric\Bundle\HealthCheckBundle\Controller\HealthCheckController
    methods: GET
immediate_health_check_trailing_slash:
    path: /healthcheck/
    controller: IM\Fabric\Bundle\HealthCheckBundle\Controller\HealthCheckController
    methods: GET
